{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vsurf
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/VSURF_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/VSURF/VSURF_{{ version }}.tar.gz
  sha256: c027b1e19762f1eaf4a559c2592f3530210fefd21ee3d7c787c73b776c683393

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base >=4.2
    - r-doparallel
    - r-foreach
    - r-randomforest
    - r-rpart
  run:
    - r-base >=4.2
    - r-doparallel
    - r-foreach
    - r-randomforest
    - r-rpart

test:
  commands:
    - $R -e "library('VSURF')"           # [not win]
    - "\"%R%\" -e \"library('VSURF')\""  # [win]

about:
  home: https://github.com/robingenuer/VSURF
  license: GPL-2.0-or-later
  summary: Three steps variable selection procedure based on random forests. Initially developed to handle high dimensional data (for which number of variables largely exceeds number of observations), the package is very versatile and can treat most dimensions of data, for regression and supervised classification problems.
    First step is dedicated to eliminate irrelevant variables from the dataset. Second step aims to select all variables related to the response for interpretation purpose. Third step refines the selection by eliminating redundancy in the set of variables selected by the second step, for prediction purpose. Genuer, R. Poggi,
    J.-M. and Tuleau-Malot, C. (2015) <https://journal.r-project.org/archive/2015-2/genuer-poggi-tuleaumalot.pdf>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
